# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 611)
        MainWindow.setStyleSheet("background-color: rgb(16, 16, 20);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(200, -1, 200, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pagesStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.pagesStackedWidget.setObjectName("pagesStackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.homeContainerFrame = QtWidgets.QFrame(self.homePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeContainerFrame.sizePolicy().hasHeightForWidth())
        self.homeContainerFrame.setSizePolicy(sizePolicy)
        self.homeContainerFrame.setStyleSheet("background-color: transparent;")
        self.homeContainerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.homeContainerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.homeContainerFrame.setObjectName("homeContainerFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.homeContainerFrame)
        self.verticalLayout_3.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_3.setSpacing(60)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeTitleLabel = QtWidgets.QLabel(self.homeContainerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeTitleLabel.sizePolicy().hasHeightForWidth())
        self.homeTitleLabel.setSizePolicy(sizePolicy)
        self.homeTitleLabel.setStyleSheet("@font-face {\n"
"       font-family: \"Soleil\";\n"
"       src: url(\"fonts/SoleilRegular.ttf\");\n"
"   }\n"
"\n"
"   QLabel {\n"
"       font-family: \"Soleil\";\n"
"       font-size: 22pt;\n"
"       color: #f7f7f7;\n"
"       font-weight: normal;\n"
"   }")
        self.homeTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.homeTitleLabel.setObjectName("homeTitleLabel")
        self.verticalLayout_3.addWidget(self.homeTitleLabel)
        self.homeBrowseButton = QtWidgets.QPushButton(self.homeContainerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeBrowseButton.sizePolicy().hasHeightForWidth())
        self.homeBrowseButton.setSizePolicy(sizePolicy)
        self.homeBrowseButton.setMinimumSize(QtCore.QSize(400, 0))
        self.homeBrowseButton.setStyleSheet("@font-face {\n"
"    font-family: \"Soleil\";\n"
"    src: url(\"fonts/SoleilRegular.ttf\");\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2D81FF;\n"
"    color: #f7f7f7;\n"
"    border: none;\n"
"    font-family: \"Soleil\";\n"
"    font-size: 10pt;\n"
"    outline: none;\n"
"    padding: 14px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4291FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1D71EF;\n"
"    color: #e0e0e0;\n"
"}")
        self.homeBrowseButton.setObjectName("homeBrowseButton")
        self.verticalLayout_3.addWidget(self.homeBrowseButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.homeContainerFrame)
        self.pagesStackedWidget.addWidget(self.homePage)
        self.transcribePage = QtWidgets.QWidget()
        self.transcribePage.setObjectName("transcribePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.transcribePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.transcribeContainerFrame = QtWidgets.QFrame(self.transcribePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transcribeContainerFrame.sizePolicy().hasHeightForWidth())
        self.transcribeContainerFrame.setSizePolicy(sizePolicy)
        self.transcribeContainerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transcribeContainerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transcribeContainerFrame.setObjectName("transcribeContainerFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.transcribeContainerFrame)
        self.verticalLayout_5.setSpacing(25)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.transcribeProgressLabel = QtWidgets.QLabel(self.transcribeContainerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transcribeProgressLabel.sizePolicy().hasHeightForWidth())
        self.transcribeProgressLabel.setSizePolicy(sizePolicy)
        self.transcribeProgressLabel.setStyleSheet("@font-face {\n"
"       font-family: \"Soleil\";\n"
"       src: url(\"fonts/SoleilRegular.ttf\");\n"
"   }\n"
"\n"
"   QLabel {\n"
"       font-family: \"Soleil\";\n"
"       font-size: 12pt;\n"
"       color: #f7f7f7;\n"
"       font-weight: normal;\n"
"   }")
        self.transcribeProgressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.transcribeProgressLabel.setObjectName("transcribeProgressLabel")
        self.verticalLayout_5.addWidget(self.transcribeProgressLabel)
        self.audioTitleFrame = QtWidgets.QFrame(self.transcribeContainerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audioTitleFrame.sizePolicy().hasHeightForWidth())
        self.audioTitleFrame.setSizePolicy(sizePolicy)
        self.audioTitleFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.audioTitleFrame.setStyleSheet("QFrame {\n"
"\n"
"background-color: #1A1A1F;\n"
"\n"
"}")
        self.audioTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.audioTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.audioTitleFrame.setObjectName("audioTitleFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.audioTitleFrame)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.audioIconLabel = QtWidgets.QLabel(self.audioTitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audioIconLabel.sizePolicy().hasHeightForWidth())
        self.audioIconLabel.setSizePolicy(sizePolicy)
        self.audioIconLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.audioIconLabel.setText("")
                # Get the directory where the script is located
        script_dir = os.path.dirname(os.path.abspath(__file__))

        # Construct the path to the icon
        icon_path = os.path.join(script_dir, "icons", "audio.svg")
        self.audioIconLabel.setPixmap(QtGui.QPixmap(icon_path))
        self.audioIconLabel.setScaledContents(True)
        self.audioIconLabel.setObjectName("audioIconLabel")
        self.horizontalLayout.addWidget(self.audioIconLabel)
        self.audioFilenameLabel = QtWidgets.QLabel(self.audioTitleFrame)
        self.audioFilenameLabel.setStyleSheet("@font-face {\n"
"       font-family: \"Soleil\";\n"
"       src: url(\"fonts/SoleilRegular.ttf\");\n"
"   }\n"
"\n"
"   QLabel {\n"
"       font-family: \"Soleil\";\n"
"       font-size: 14pt;\n"
"       color: #f7f7f7;\n"
"       font-weight: normal;\n"
"   }")
        self.audioFilenameLabel.setObjectName("audioFilenameLabel")
        self.horizontalLayout.addWidget(self.audioFilenameLabel)
        self.verticalLayout_5.addWidget(self.audioTitleFrame)
        self.verticalLayout_2.addWidget(self.transcribeContainerFrame)
        self.pagesStackedWidget.addWidget(self.transcribePage)
        self.transcriptionResultPage = QtWidgets.QWidget()
        self.transcriptionResultPage.setObjectName("transcriptionResultPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.transcriptionResultPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.resultContainerFrame = QtWidgets.QFrame(self.transcriptionResultPage)
        self.resultContainerFrame.setStyleSheet("background-color: transparent;")
        self.resultContainerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resultContainerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resultContainerFrame.setObjectName("resultContainerFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.resultContainerFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.resultTopBarFrame = QtWidgets.QFrame(self.resultContainerFrame)
        self.resultTopBarFrame.setStyleSheet("background-color: transparent;")
        self.resultTopBarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resultTopBarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resultTopBarFrame.setObjectName("resultTopBarFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.resultTopBarFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resultTitleBarLabel = QtWidgets.QLabel(self.resultTopBarFrame)
        self.resultTitleBarLabel.setStyleSheet("@font-face {\n"
"       font-family: \"Soleil\";\n"
"       src: url(\"fonts/SoleilRegular.ttf\");\n"
"   }\n"
"\n"
"   QLabel {\n"
"       font-family: \"Soleil\";\n"
"       font-size: 13pt;\n"
"       color: #f7f7f7;\n"
"       font-weight: normal;\n"
"   }")
        self.resultTitleBarLabel.setObjectName("resultTitleBarLabel")
        self.horizontalLayout_2.addWidget(self.resultTitleBarLabel)
        self.fileTypeComboBox = QtWidgets.QComboBox(self.resultTopBarFrame)
        self.fileTypeComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #2a2a2a;\n"
"    color: #ffffff;\n"
"    border: 1px solid #3a3a3a;\n"
"    border-radius:53px;\n"
"    padding: 11px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left: 1px solid #3a3a3a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2a2a2a;\n"
"    color: #ffffff;\n"
"    border: 1px solid #3a3a3a;\n"
"    selection-background-color: #3a3a3a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 25px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #3a3a3a;\n"
"}")
        self.fileTypeComboBox.setObjectName("fileTypeComboBox")
        self.fileTypeComboBox.addItem("")
        self.fileTypeComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.fileTypeComboBox)
        self.pushButton = QtWidgets.QPushButton(self.resultTopBarFrame)
        self.pushButton.setStyleSheet("@font-face {\n"
"    font-family: \"Soleil\";\n"
"    src: url(\"fonts/SoleilRegular.ttf\");\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2D81FF;\n"
"    color: #fff;\n"
"    border: none;\n"
"    font-family: \"Soleil\";\n"
"    font-size: 10pt;\n"
"    outline: none;\n"
"    padding: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4291FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1D71EF;\n"
"    color: #e0e0e0;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_7.addWidget(self.resultTopBarFrame)
        self.transcriptionFrame = QtWidgets.QFrame(self.resultContainerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transcriptionFrame.sizePolicy().hasHeightForWidth())
        self.transcriptionFrame.setSizePolicy(sizePolicy)
        self.transcriptionFrame.setStyleSheet("QFrame#transcriptionFrame {\n"
"background-color: #1A1A1F;\n"
"border: 1px solid #2C2C33;\n"
"}")
        self.transcriptionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transcriptionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transcriptionFrame.setObjectName("transcriptionFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.transcriptionFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.transcriptionFrame)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollArea > QWidget > QWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #2A2A2A;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #5A5A5A;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #6A6A6A;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 574, 916))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.transcriptionTextLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transcriptionTextLabel.sizePolicy().hasHeightForWidth())
        self.transcriptionTextLabel.setSizePolicy(sizePolicy)
        self.transcriptionTextLabel.setStyleSheet("@font-face {\n"
"       font-family: \"Soleil\";\n"
"       src: url(\"fonts/SoleilRegular.ttf\");\n"
"   }\n"
"\n"
"   QLabel {\n"
"       font-family: \"Soleil\";\n"
"       font-size: 10pt;\n"
"       color: #f7f7f7;\n"
"       font-weight: normal;\n"
"   }")
        self.transcriptionTextLabel.setScaledContents(False)
        self.transcriptionTextLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.transcriptionTextLabel.setWordWrap(True)
        self.transcriptionTextLabel.setObjectName("transcriptionTextLabel")
        self.horizontalLayout_3.addWidget(self.transcriptionTextLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.verticalLayout_7.addWidget(self.transcriptionFrame)
        self.verticalLayout_6.addWidget(self.resultContainerFrame)
        self.pagesStackedWidget.addWidget(self.transcriptionResultPage)
        self.verticalLayout.addWidget(self.pagesStackedWidget)
        self.newTranscriptionButton = QtWidgets.QPushButton(self.centralwidget)
        self.newTranscriptionButton.setStyleSheet("@font-face {\n"
"    font-family: \"Soleil\";\n"
"    src: url(\"fonts/SoleilRegular.ttf\");\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #343940;\n"
"    color: #fff;\n"
"    border: none;\n"
"    font-family: \"Soleil\";\n"
"    font-size: 10pt;\n"
"    outline: none;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #434952;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #24272b;\n"
"    color: #e0e0e0;\n"
"}")
        self.newTranscriptionButton.setObjectName("newTranscriptionButton")
        self.verticalLayout.addWidget(self.newTranscriptionButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pagesStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scribey"))
        self.homeTitleLabel.setText(_translate("MainWindow", "Choose an audio file to transcribe."))
        self.homeBrowseButton.setText(_translate("MainWindow", "Browse Files"))
        self.transcribeProgressLabel.setText(_translate("MainWindow", "Currently transcribing audio... 0%"))
        self.audioFilenameLabel.setText(_translate("MainWindow", "jre.wav"))
        self.resultTitleBarLabel.setText(_translate("MainWindow", "Your Transcription"))
        self.fileTypeComboBox.setItemText(0, _translate("MainWindow", "Captions (.SRT File)"))
        self.fileTypeComboBox.setItemText(1, _translate("MainWindow", "Transcript (.txt File)"))
        self.pushButton.setText(_translate("MainWindow", "Download"))
        self.newTranscriptionButton.setText(_translate("MainWindow", "New Transcription"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
